//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_21_22
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idBook { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
